name: CI
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
      link:
        required: true
        type: choice       
jobs:
  Download:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download
        run: |
          sudo mkdir /download && cd /download
          sudo ${{ inputs.link }}
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.name }}
          name: ${{ inputs.name }}
          body: Download File
          draft: false
          prerelease: false
          files: /download/*
  Send_Email:
    needs: Download
    runs-on: ubuntu-22.04
    name: 'Send mail'
    steps:
      - uses: dawidd6/action-send-mail@master
        with:
          server_address: ${{  secrets.SMTP }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Download Report
          body: file://Download.txt
          to: ${{ secrets.MAILADD }}
          from: GitHub Actions
          content_type: text/plain
